<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Interpreter.Product.StaticAnalysis</AssemblyName>
    <RootNamespace>Interpreter.Product.StaticAnalysis</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Interpreter.Metadata.SRM/Interpreter.Metadata.SRM.csproj" />
    <ProjectReference Include="../Interpreter.Core.IR/Interpreter.Core.IR.csproj" />
    <ProjectReference Include="../Interpreter.Core.Analysis/Interpreter.Core.Analysis.csproj" />
    <ProjectReference Include="../Interpreter.Domain.CNTypeTaint/Interpreter.Domain.CNTypeTaint.csproj" />
    <ProjectReference Include="../Interpreter.Domain.Range/Interpreter.Domain.Range.csproj" />
    <ProjectReference Include="../Interpreter.Memory.SummaryHeap/Interpreter.Memory.SummaryHeap.csproj" />
    <ProjectReference Include="../Interpreter.Models.Environment/Interpreter.Models.Environment.csproj" />
    <ProjectReference Include="../Interpreter.Models.CompilerPatterns/Interpreter.Models.CompilerPatterns.csproj" />
  </ItemGroup>
</Project>
