<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Interpreter.Types</AssemblyName>
    <RootNamespace>Interpreter.Types</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Interpreter.Foundation/Interpreter.Foundation.csproj" />
  </ItemGroup>
</Project>
