<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Interpreter.DebugMaps</AssemblyName>
    <RootNamespace>Interpreter.DebugMaps</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Interpreter.Metadata.Abstractions/Interpreter.Metadata.Abstractions.csproj" />
    <ProjectReference Include="../Interpreter.Foundation/Interpreter.Foundation.csproj" />
  </ItemGroup>
</Project>
