<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Interpreter.Models.Abstractions</AssemblyName>
    <RootNamespace>Interpreter.Models.Abstractions</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Interpreter.Core.Abstractions/Interpreter.Core.Abstractions.csproj" />
    <ProjectReference Include="../Interpreter.Foundation/Interpreter.Foundation.csproj" />
  </ItemGroup>
</Project>
