<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Interpreter.W7PdbConflictFixture</AssemblyName>
    <RootNamespace>Interpreter.W7PdbConflictFixture</RootNamespace>
    <Optimize>true</Optimize>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
