<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Interpreter.Decompiler.ILSpy</AssemblyName>
    <RootNamespace>Interpreter.Decompiler.ILSpy</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Interpreter.Metadata.Abstractions/Interpreter.Metadata.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ICSharpCode.Decompiler" Version="8.2.0.7535" />
  </ItemGroup>
</Project>
