<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Interpreter.Metadata.SRM</AssemblyName>
    <RootNamespace>Interpreter.Metadata.SRM</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Interpreter.Metadata.Abstractions/Interpreter.Metadata.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Reflection.Metadata" Version="9.0.0" />
  </ItemGroup>
</Project>
