<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Interpreter.TestTarget</AssemblyName>
    <RootNamespace>Interpreter.TestTarget</RootNamespace>
    <Optimize>true</Optimize>
    <DebugType>portable</DebugType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
