<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Interpreter.Host.Runtime.Sandbox</AssemblyName>
    <RootNamespace>Interpreter.Host.Runtime.Sandbox</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Interpreter.Host.Abstractions/Interpreter.Host.Abstractions.csproj" />
    <ProjectReference Include="../Interpreter.Memory.VirtualHeap/Interpreter.Memory.VirtualHeap.csproj" />
    <ProjectReference Include="../Interpreter.Domain.Concrete/Interpreter.Domain.Concrete.csproj" />
  </ItemGroup>
</Project>
