using System.Collections.Immutable;

namespace PhoenixInspect.Core.Abstractions;

/// <summary>Classifies the top-level source boundary from which an evaluation obtained its evidence.</summary>
/// <remarks>
/// This classification is backend-neutral: it describes the identity and replay boundary, not the library used to
/// decode it. Ordered <see cref="EvaluationProvenance"/> entries retain the more granular sources and
/// transformations that support an individual answer.
/// </remarks>
public enum EvaluationEvidenceSourceKind
{
    /// <summary>No external evidence source applies to this result.</summary>
    None,

    /// <summary>Evidence was obtained from one immutable, content-identified process dump snapshot.</summary>
    DumpSnapshot,

    /// <summary>Evidence was obtained from one separately acquired, content-identified artifact.</summary>
    Artifact,

    /// <summary>Evidence was generated by a deterministic synthetic fixture rather than captured target state.</summary>
    Synthetic,
}

/// <summary>Classifies whether a stable snapshot or module identity applies and was established.</summary>
public enum EvaluationIdentityAvailability
{
    /// <summary>The identity category does not apply to this evaluation source.</summary>
    NotApplicable,

    /// <summary>A stable identity was established and is carried by the context.</summary>
    Available,

    /// <summary>The identity category applies, but no compatible identity could be established.</summary>
    Unavailable,
}

/// <summary>Represents an explicit stable-identity outcome without using a missing value as an implicit status.</summary>
public sealed record EvaluationEvidenceIdentity
{
    private const int MaximumSourceIdLength = 1_024;

    private EvaluationEvidenceIdentity(EvaluationIdentityAvailability availability, string? sourceId)
    {
        Availability = availability;
        SourceId = sourceId;
    }

    /// <summary>
    /// Gets the shared identity outcome used when a snapshot or module category does not apply to the evidence source.
    /// </summary>
    public static EvaluationEvidenceIdentity NotApplicable { get; } =
        new(EvaluationIdentityAvailability.NotApplicable, null);

    /// <summary>
    /// Gets the shared identity outcome used when the category applies but no compatible stable identity is known.
    /// </summary>
    public static EvaluationEvidenceIdentity Unavailable { get; } =
        new(EvaluationIdentityAvailability.Unavailable, null);

    /// <summary>Gets whether the identity is available, unavailable, or inapplicable.</summary>
    public EvaluationIdentityAvailability Availability { get; }

    /// <summary>
    /// Gets the stable source identity when <see cref="Availability"/> is
    /// <see cref="EvaluationIdentityAvailability.Available"/>; otherwise, gets <see langword="null"/> as an
    /// explicit consequence of the availability status.
    /// </summary>
    public string? SourceId { get; }

    /// <summary>Creates an available identity from a stable, path-independent source identifier.</summary>
    /// <param name="sourceId">
    /// A non-empty identifier of at most 1024 printable non-whitespace characters. Callers should prefer
    /// content-derived and versioned identifiers over display names or local paths.
    /// </param>
    /// <returns>An identity outcome whose availability is <see cref="EvaluationIdentityAvailability.Available"/>.</returns>
    /// <exception cref="ArgumentException">
    /// <paramref name="sourceId"/> is empty, too long, contains whitespace, or contains a control character.
    /// </exception>
    public static EvaluationEvidenceIdentity CreateAvailable(string sourceId)
    {
        if (string.IsNullOrWhiteSpace(sourceId))
        {
            throw new ArgumentException("A stable evidence identity is required.", nameof(sourceId));
        }

        if (sourceId.Length > MaximumSourceIdLength)
        {
            throw new ArgumentException(
                $"Evidence identities are limited to {MaximumSourceIdLength} characters.",
                nameof(sourceId));
        }

        if (sourceId.Any(static character => char.IsWhiteSpace(character) || char.IsControl(character)))
        {
            throw new ArgumentException(
                "Evidence identities cannot contain whitespace or control characters.",
                nameof(sourceId));
        }

        return new EvaluationEvidenceIdentity(EvaluationIdentityAvailability.Available, sourceId);
    }
}

/// <summary>Classifies whether an evidence fallback changed the source used to answer an evaluation.</summary>
public enum EvaluationFallbackStatus
{
    /// <summary>No evidence fallback was attempted or applied.</summary>
    None,

    /// <summary>A named, explicit fallback supplied evidence used by the result.</summary>
    Applied,
}

/// <summary>Records an explicit fallback outcome, including the no-fallback outcome.</summary>
public sealed record EvaluationFallback
{
    private const string NoneName = "none";

    private EvaluationFallback(EvaluationFallbackStatus status, string name)
    {
        Status = status;
        Name = name;
    }

    /// <summary>Gets the shared explicit outcome used when no fallback was attempted or applied.</summary>
    public static EvaluationFallback None { get; } = new(EvaluationFallbackStatus.None, NoneName);

    /// <summary>Gets whether no fallback occurred or a named fallback was applied.</summary>
    public EvaluationFallbackStatus Status { get; }

    /// <summary>
    /// Gets the stable fallback name, or the canonical name <c>none</c> when <see cref="Status"/> is
    /// <see cref="EvaluationFallbackStatus.None"/>.
    /// </summary>
    public string Name { get; }

    /// <summary>Creates an explicit applied-fallback outcome.</summary>
    /// <param name="name">
    /// A stable lowercase name beginning with a letter and containing only lowercase ASCII letters, digits, periods,
    /// and hyphens. The reserved name <c>none</c> cannot identify an applied fallback.
    /// </param>
    /// <returns>A fallback outcome whose status is <see cref="EvaluationFallbackStatus.Applied"/>.</returns>
    /// <exception cref="ArgumentException"><paramref name="name"/> is not a stable canonical name.</exception>
    public static EvaluationFallback CreateApplied(string name)
    {
        EvaluationContextName.Validate(name, nameof(name));
        if (string.Equals(name, NoneName, StringComparison.Ordinal))
        {
            throw new ArgumentException("The reserved name 'none' cannot identify an applied fallback.", nameof(name));
        }

        return new EvaluationFallback(EvaluationFallbackStatus.Applied, name);
    }
}

/// <summary>Records one named, numeric deterministic bound that constrained an evaluation operation.</summary>
public sealed record EvaluationDeterministicBound
{
    /// <summary>Creates a validated deterministic bound.</summary>
    /// <param name="name">
    /// A stable lowercase semantic name beginning with a letter and containing only lowercase ASCII letters, digits,
    /// periods, and hyphens. The name should include the unit, such as <c>query.expression.characters</c>.
    /// </param>
    /// <param name="value">The non-negative inclusive upper bound applied by the operation.</param>
    /// <exception cref="ArgumentException"><paramref name="name"/> is not a stable canonical name.</exception>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="value"/> is negative.</exception>
    public EvaluationDeterministicBound(string name, long value)
    {
        EvaluationContextName.Validate(name, nameof(name));
        if (value < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(value), "A deterministic bound cannot be negative.");
        }

        Name = name;
        Value = value;
    }

    /// <summary>Gets the stable semantic name, including the bound's unit.</summary>
    public string Name { get; }

    /// <summary>Gets the non-negative inclusive upper bound applied by the operation.</summary>
    public long Value { get; }
}

/// <summary>
/// Carries backend-neutral snapshot, module, source, fallback, and deterministic-bound context for an evaluation.
/// </summary>
/// <remarks>
/// The context is immutable and normalizes bounds into ordinal name order so semantically identical inputs have one
/// canonical replay representation. Its neutral instance is explicit: result consumers never need to infer that a
/// missing context means identities or external evidence did not apply.
/// </remarks>
public sealed class EvaluationEvidenceContext
{
    private readonly ImmutableArray<EvaluationDeterministicBound> bounds;

    private EvaluationEvidenceContext(
        EvaluationEvidenceSourceKind sourceKind,
        EvaluationEvidenceIdentity snapshot,
        EvaluationEvidenceIdentity module,
        EvaluationFallback fallback,
        ImmutableArray<EvaluationDeterministicBound> bounds)
    {
        SourceKind = sourceKind;
        Snapshot = snapshot;
        Module = module;
        Fallback = fallback;
        this.bounds = Copy(bounds);
    }

    /// <summary>
    /// Gets the shared explicit context for results to which no external evidence identity, fallback, or bound applies.
    /// </summary>
    public static EvaluationEvidenceContext Neutral { get; } = new(
        EvaluationEvidenceSourceKind.None,
        EvaluationEvidenceIdentity.NotApplicable,
        EvaluationEvidenceIdentity.NotApplicable,
        EvaluationFallback.None,
        ImmutableArray<EvaluationDeterministicBound>.Empty);

    /// <summary>Gets the top-level evidence source classification.</summary>
    public EvaluationEvidenceSourceKind SourceKind { get; }

    /// <summary>Gets the explicit snapshot identity outcome.</summary>
    public EvaluationEvidenceIdentity Snapshot { get; }

    /// <summary>Gets the explicit module identity outcome.</summary>
    public EvaluationEvidenceIdentity Module { get; }

    /// <summary>Gets the explicit named fallback outcome, including the no-fallback outcome.</summary>
    public EvaluationFallback Fallback { get; }

    /// <summary>
    /// Gets a defensive copy containing only the deterministic bounds actually applied on this outcome's execution
    /// path, in ordinal name order. Configured limits whose guarded operation was not reached are intentionally
    /// absent.
    /// </summary>
    public ImmutableArray<EvaluationDeterministicBound> Bounds => Copy(bounds);

    /// <summary>Creates a validated immutable evidence context.</summary>
    /// <param name="sourceKind">The top-level external evidence-source classification.</param>
    /// <param name="snapshot">The explicit snapshot identity outcome.</param>
    /// <param name="module">The explicit module identity outcome.</param>
    /// <param name="fallback">The explicit fallback outcome.</param>
    /// <param name="bounds">
    /// The complete set of deterministic bounds actually applied by this operation. A default array is normalized to
    /// empty; entries must be non-null and names must be unique. Caller order is not retained.
    /// </param>
    /// <returns>A context with bounds normalized into ordinal name order.</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="sourceKind"/> is not defined.</exception>
    /// <exception cref="ArgumentNullException">
    /// <paramref name="snapshot"/>, <paramref name="module"/>, or <paramref name="fallback"/> is
    /// <see langword="null"/>.
    /// </exception>
    /// <exception cref="ArgumentException">
    /// The source and identity outcomes conflict, or <paramref name="bounds"/> contains a null entry or duplicate name.
    /// </exception>
    public static EvaluationEvidenceContext Create(
        EvaluationEvidenceSourceKind sourceKind,
        EvaluationEvidenceIdentity snapshot,
        EvaluationEvidenceIdentity module,
        EvaluationFallback fallback,
        ImmutableArray<EvaluationDeterministicBound> bounds = default)
    {
        if (!Enum.IsDefined(sourceKind))
        {
            throw new ArgumentOutOfRangeException(nameof(sourceKind));
        }

        ArgumentNullException.ThrowIfNull(snapshot);
        ArgumentNullException.ThrowIfNull(module);
        ArgumentNullException.ThrowIfNull(fallback);

        var normalizedBounds = bounds.IsDefault
            ? ImmutableArray<EvaluationDeterministicBound>.Empty
            : bounds;
        if (normalizedBounds.Any(static bound => bound is null))
        {
            throw new ArgumentException("Deterministic bounds cannot contain null entries.", nameof(bounds));
        }

        normalizedBounds = normalizedBounds
            .OrderBy(static bound => bound.Name, StringComparer.Ordinal)
            .ToImmutableArray();
        for (var index = 1; index < normalizedBounds.Length; index++)
        {
            if (string.Equals(normalizedBounds[index - 1].Name, normalizedBounds[index].Name, StringComparison.Ordinal))
            {
                throw new ArgumentException(
                    $"The deterministic bound name '{normalizedBounds[index].Name}' occurs more than once.",
                    nameof(bounds));
            }
        }

        if (sourceKind == EvaluationEvidenceSourceKind.None)
        {
            if (snapshot.Availability != EvaluationIdentityAvailability.NotApplicable ||
                module.Availability != EvaluationIdentityAvailability.NotApplicable ||
                fallback.Status != EvaluationFallbackStatus.None ||
                !normalizedBounds.IsEmpty)
            {
                throw new ArgumentException(
                    "A context without an evidence source must use inapplicable identities, no fallback, and no bounds.",
                    nameof(sourceKind));
            }

            return Neutral;
        }

        if (sourceKind == EvaluationEvidenceSourceKind.DumpSnapshot)
        {
            if (snapshot.Availability != EvaluationIdentityAvailability.Available)
            {
                throw new ArgumentException("Dump-snapshot evidence requires an available snapshot identity.", nameof(snapshot));
            }

            if (module.Availability == EvaluationIdentityAvailability.NotApplicable)
            {
                throw new ArgumentException(
                    "Dump-snapshot evidence requires an explicit available or unavailable module outcome.",
                    nameof(module));
            }
        }

        return new EvaluationEvidenceContext(
            sourceKind,
            snapshot,
            module,
            fallback,
            normalizedBounds);
    }

    private static ImmutableArray<T> Copy<T>(ImmutableArray<T> values) =>
        values.IsDefaultOrEmpty
            ? ImmutableArray<T>.Empty
            : ImmutableArray.CreateRange(values.AsSpan().ToArray());
}

internal static class EvaluationContextName
{
    private const int MaximumNameLength = 128;

    internal static void Validate(string name, string parameterName)
    {
        if (string.IsNullOrWhiteSpace(name) ||
            name.Length > MaximumNameLength ||
            name[0] is < 'a' or > 'z' ||
            name.Any(static character => character is not (>= 'a' and <= 'z') and
                not (>= '0' and <= '9') and not '.' and not '-'))
        {
            throw new ArgumentException(
                "A stable lowercase name beginning with a letter and containing only letters, digits, periods, and hyphens is required.",
                parameterName);
        }
    }
}
