<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PhoenixInspect.Core.Execution</AssemblyName>
    <RootNamespace>PhoenixInspect.Core.Execution</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PhoenixInspect.Core.Abstractions/PhoenixInspect.Core.Abstractions.csproj" />
  </ItemGroup>
</Project>
