namespace Interpreter.Abstractions;

/// <summary>
/// Captures the reason a checkpoint snapshot was persisted for an execution session.
/// </summary>
/// <remarks>
/// The reason taxonomy is intentionally compact during the prototype phase so hosts can evaluate retention and rewind UX
/// behavior before we commit to a richer event model.
/// </remarks>
public enum SessionCheckpointReason
{
    /// <summary>
    /// Indicates that the checkpoint was taken automatically after a stepping command reached a stable host-visible boundary.
    /// </summary>
    StepBoundary,

    /// <summary>
    /// Indicates that the checkpoint was taken because the engine reached a stop condition or terminal state.
    /// </summary>
    StopBoundary,

    /// <summary>
    /// Indicates that the checkpoint was captured due to explicit host request.
    /// </summary>
    HostRequested,
}

/// <summary>
/// Represents an immutable session snapshot that can be stored, replayed, or restored by prototype hosts.
/// </summary>
/// <param name="SessionId">Gets the stable execution session identifier for correlation with diagnostics and requests.</param>
/// <param name="Revision">Gets the monotonically increasing snapshot revision assigned by the session store.</param>
/// <param name="LifecycleState">Gets the lifecycle state captured when the snapshot was materialized.</param>
/// <param name="ActiveMethodIdentity">Gets the fully qualified method identity of the currently active frame.</param>
/// <param name="InstructionOffset">Gets the active instruction pointer offset for the top frame at capture time.</param>
/// <param name="CapturedUtc">Gets the UTC timestamp when the snapshot was created by the host or engine coordinator.</param>
/// <param name="StateSlots">Gets a draft key/value bag for lightweight session state values tracked during concept validation.</param>
/// <param name="CallStack">Gets the ordered call stack snapshot from root frame to active frame at capture time.</param>
/// <remarks>
/// This record intentionally keeps state payloads loosely typed so architecture discussions can refine state shape and
/// persistence strategy without expensive migration overhead.
/// </remarks>
public sealed record ExecutionSessionSnapshot(
    string SessionId,
    long Revision,
    ExecutionLifecycleState LifecycleState,
    string ActiveMethodIdentity,
    int InstructionOffset,
    DateTimeOffset CapturedUtc,
    IReadOnlyDictionary<string, string> StateSlots,
    IReadOnlyList<ExecutionFrameSnapshot> CallStack);

/// <summary>
/// Describes a stored checkpoint marker that can be listed independently from full session snapshot payloads.
/// </summary>
/// <param name="SessionId">Gets the execution session identifier that owns the checkpoint.</param>
/// <param name="Revision">Gets the snapshot revision associated with this checkpoint marker.</param>
/// <param name="Reason">Gets the reason the checkpoint was recorded by the host or execution coordinator.</param>
/// <param name="Label">Gets a host-visible label that can be shown in debugging UI timelines.</param>
/// <param name="CapturedUtc">Gets the UTC timestamp associated with checkpoint creation.</param>
/// <remarks>
/// This descriptor exists so hosts can build timeline and rewind affordances without materializing full snapshot content.
/// </remarks>
public sealed record SessionCheckpointDescriptor(
    string SessionId,
    long Revision,
    SessionCheckpointReason Reason,
    string Label,
    DateTimeOffset CapturedUtc);

/// <summary>
/// Defines the draft persistence seam for execution session snapshots and checkpoint metadata.
/// </summary>
/// <remarks>
/// Implementations may store snapshots in-memory, on disk, or in host-managed persistence layers.
/// The contract is deliberately async-first so hosts can experiment with remote stores while still preserving deterministic
/// replay ordering semantics.
/// </remarks>
public interface IExecutionSessionStore
{
    /// <summary>
    /// Persists a new immutable snapshot revision for the specified execution session.
    /// </summary>
    /// <param name="snapshot">The full session snapshot payload to store.</param>
    /// <param name="checkpointReason">The reason that this snapshot is being persisted as a checkpoint boundary.</param>
    /// <param name="checkpointLabel">
    /// A host-visible label for the checkpoint, such as <c>step-over@IL_0034</c> or <c>session-completed</c>.
    /// </param>
    /// <param name="cancellationToken">A token that aborts persistence when host cancellation is requested.</param>
    /// <returns>
    /// A value task that resolves to the checkpoint descriptor generated by the store, including normalized revision metadata.
    /// </returns>
    ValueTask<SessionCheckpointDescriptor> SaveSnapshotAsync(
        ExecutionSessionSnapshot snapshot,
        SessionCheckpointReason checkpointReason,
        string checkpointLabel,
        CancellationToken cancellationToken);

    /// <summary>
    /// Attempts to read a stored snapshot for the specified session and revision.
    /// </summary>
    /// <param name="sessionId">The execution session identifier to query.</param>
    /// <param name="revision">The snapshot revision to retrieve. Hosts should pass the latest known revision for rewind previews.</param>
    /// <param name="cancellationToken">A token that aborts retrieval work when host cancellation is requested.</param>
    /// <returns>
    /// A value task that resolves to the stored snapshot when available; otherwise <see langword="null"/>.
    /// </returns>
    ValueTask<ExecutionSessionSnapshot?> TryGetSnapshotAsync(
        string sessionId,
        long revision,
        CancellationToken cancellationToken);

    /// <summary>
    /// Lists checkpoint markers for the specified session ordered from newest to oldest.
    /// </summary>
    /// <param name="sessionId">The execution session identifier whose checkpoint timeline should be enumerated.</param>
    /// <param name="maxCount">The maximum number of checkpoint markers to return for this request.</param>
    /// <param name="cancellationToken">A token that aborts enumeration work when host cancellation is requested.</param>
    /// <returns>
    /// A value task that resolves to checkpoint descriptors for timeline rendering and rewind selection.
    /// </returns>
    ValueTask<IReadOnlyList<SessionCheckpointDescriptor>> ListCheckpointsAsync(
        string sessionId,
        int maxCount,
        CancellationToken cancellationToken);
}
