<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Interpreter.Host.Dump.ClrMD</AssemblyName>
    <RootNamespace>Interpreter.Host.Dump.ClrMD</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Interpreter.Core.Abstractions/Interpreter.Core.Abstractions.csproj" />
    <ProjectReference Include="../Interpreter.Host.Abstractions/Interpreter.Host.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Diagnostics.Runtime" />
  </ItemGroup>
</Project>
