<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Interpreter.Product.DumpDebugging</AssemblyName>
    <RootNamespace>Interpreter.Product.DumpDebugging</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Interpreter.Host.Dump.ClrMD/Interpreter.Host.Dump.ClrMD.csproj" />
    <ProjectReference Include="../Interpreter.Metadata.SRM/Interpreter.Metadata.SRM.csproj" />
    <ProjectReference Include="../Interpreter.Symbols.PortablePdb/Interpreter.Symbols.PortablePdb.csproj" />
    <ProjectReference Include="../Interpreter.Decompiler.ILSpy/Interpreter.Decompiler.ILSpy.csproj" />
    <ProjectReference Include="../Interpreter.DebugMaps/Interpreter.DebugMaps.csproj" />
    <ProjectReference Include="../Interpreter.Debugger.Engine/Interpreter.Debugger.Engine.csproj" />
    <ProjectReference Include="../Interpreter.Domain.CNTypeTaint/Interpreter.Domain.CNTypeTaint.csproj" />
    <ProjectReference Include="../Interpreter.Memory.VirtualHeap/Interpreter.Memory.VirtualHeap.csproj" />
    <ProjectReference Include="../Interpreter.Memory.Overlay/Interpreter.Memory.Overlay.csproj" />
    <ProjectReference Include="../Interpreter.Models.CoreLib.Primitives/Interpreter.Models.CoreLib.Primitives.csproj" />
    <ProjectReference Include="../Interpreter.Models.Environment/Interpreter.Models.Environment.csproj" />
    <ProjectReference Include="../Interpreter.Models.Async/Interpreter.Models.Async.csproj" />
    <ProjectReference Include="../Interpreter.Models.Dynamic/Interpreter.Models.Dynamic.csproj" />
    <ProjectReference Include="../Interpreter.Models.Collections/Interpreter.Models.Collections.csproj" />
    <ProjectReference Include="../Interpreter.Models.CompilerPatterns/Interpreter.Models.CompilerPatterns.csproj" />
  </ItemGroup>
</Project>
