<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Interpreter.Models.RoslynAdapter</AssemblyName>
    <RootNamespace>Interpreter.Models.RoslynAdapter</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Interpreter.Metadata.Abstractions/Interpreter.Metadata.Abstractions.csproj" />
    <ProjectReference Include="../Interpreter.Models.Dynamic/Interpreter.Models.Dynamic.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" />
  </ItemGroup>
</Project>
